spring.application.name=resume

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.enabled=true
#different models - testing them out
#spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.model=text-embedding-ada-002
#spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.model=gpt-5.4-nano
vector.store.name=vector-store.json

server.port=${PORT:8080}

logging.level.dev.langchain4j=DEBUG

logging.level.root=info
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.web.reactive.function.client=TRACE

management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1